"""empty message

Revision ID: 6846bb206891
Revises: 
Create Date: 2019-02-04 14:01:01.986789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6846bb206891'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pseudo', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pseudo')
    )
    op.drop_table('search_query')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_query',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('tsv', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('results', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='search_query_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
