"""empty message

Revision ID: ae8c12a9d274
Revises: c4e11e904e06
Create Date: 2019-02-04 16:49:06.315037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8c12a9d274'
down_revision = 'c4e11e904e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('folder_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_table('tsv',
    sa.Column('tsv_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.folder_id'], ),
    sa.PrimaryKeyConstraint('tsv_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tsv')
    op.drop_table('folder')
    # ### end Alembic commands ###
