"""empty message

Revision ID: c4e11e904e06
Revises: 6846bb206891
Create Date: 2019-02-04 14:01:51.541055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e11e904e06'
down_revision = '6846bb206891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_date', sa.DateTime(), nullable=False),
    sa.Column('tsv', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=500), nullable=False),
    sa.Column('results', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_query')
    # ### end Alembic commands ###
